### ISSUE TITLE
_pytest.fixtures has no attribute 'scope2props'

### ISSUE THREAD

**Issue by spencerbug** [nak/pytest_mproc#4]
Hi!

I'm using the latest pytest version 6.2.2 and the pytest developers removed scope properties (as you can see here https://github.com/pytest-dev/pytest/commit/12de92cd2b818906d342dbdfaf96999887bc9658)
So this code does not work with the latest version of pytest.

Can you update this? Which version of pytest will this work with?

**Comment by nak** [comment]
This will take some time.  I hope to have bandwidth this month but changes to pytest were substantial.  This Is tested to worth with 6.0.1 and may work with 6.0.*

**Comment by jrusnakli** [comment]
I have upload 4.0.5 which I believe will work with recent pytest versions, AS LONG AS you are not used node-level or global-level features that are added in pytest_mproc

**Comment by jrusnakli** [comment]
Resolved in version 4.1.0, pushed to pypi

**Comment by nak** [comment]
fixed in 4.1.0
